clientId: "agent-1"
routes:
  - name: "route1"
    value: "localhost"
    port: 8083
    type: "cname"
  - name: "route2"
    value: "localhost"
    port: 8084
    type: "cname"
proxyview:
  url: "localhost:8081"
  token: "xxxx-xxxx-xxxx-xxxx"