version: "3"
services:

  proxyview-server:
    container_name: server
    image: "proxyview-server:${TAG}"
    networks:
      proxyview_nw:
        aliases:
          - localhost-server
    environment:
      - ENV=development
      - LHUB_CONFIG_DIR=/opt/docker/conf
    volumes:
      - ./conf/server.yaml:/opt/docker/conf/application.yaml
    ports:
      - "8080:8080"
      - "8081:8081"

  client1:
    container_name: client1
    image: "proxyview-client:${TAG}"
    networks: ["proxyview_nw"]
    environment:
      - ENV=development
      - LHUB_CONFIG_DIR=/opt/docker/conf
    volumes:
      - ./conf/client1.yaml:/opt/docker/conf/application.yaml

  client2:
    container_name: client2
    image: "proxyview-client:${TAG}"
    networks: ["proxyview_nw"]
    environment:
      - ENV=development
      - LHUB_CONFIG_DIR=/opt/docker/conf
    volumes:
      - ./conf/client2.yaml:/opt/docker/conf/application.yaml

  sample_service:
    container_name: sample_service
    image: httpd
    networks:
      proxyview_nw:
        aliases:
          - localhost-sample
    ports:
      - "8083:80"

  sample_service2:
    container_name: sample_service2
    image: httpd
    networks:
      proxyview_nw:
        aliases:
          - localhost-sample2
    ports:
      - "8084:80"

networks:
  proxyview_nw:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.19.8.0/24