version: 2.1
jobs:
  build:
    working_directory: /root/proxyview
    docker:
      - image: docker.io/mridulverma/proxyview:circleci-v2.0
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
        environment:
          TAG: $CIRCLE_TAG
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Push the Docker Images
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            sbt proxyview-client/docker:publish
            sbt proxyview-server/docker:publish